# Generated by Django 4.2.3 on 2023-08-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_userquiz'),
        ('users', '0002_user_is_verified_user_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiz_answers',
            field=models.ManyToManyField(through='quizzes.UserQuiz', to='quizzes.quiz'),
        ),
    ]
