# Generated by Django 4.2.3 on 2023-08-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_userselection'),
        ('users', '0003_user_quiz_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='quiz_answers',
            new_name='solved_quizzes',
        ),
        migrations.AddField(
            model_name='user',
            name='selections',
            field=models.ManyToManyField(through='quizzes.UserSelection', to='quizzes.option'),
        ),
    ]
