version: '3.8'

services:
  web-api-prod:
    build:
      context: .
    image: squiz-api
    container_name: web-api-prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 -w 3
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web-api-prod