# Generated by Django 4.2.3 on 2023-08-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='option',
            table='question_option',
        ),
    ]
