# Generated by Django 4.2.3 on 2023-08-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quiz_draft_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='is_scheduled',
            new_name='use_scheduling',
        ),
    ]
