# Generated by Django 4.2.3 on 2023-08-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_rename_is_scheduled_quiz_use_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
