from .quiz import QuizCreationMutation, QuizUpdateMutation
from .question import QuestionCreationMutation, QuestionUpdateMutation
from .option import AddOptionToQuestionMutation, SetCorrectOptionMutation