from .option import AddOptionToQuestionMutation, SetCorrectOptionMutation
from .quiz import QuizCreationMutation, QuizUpdateMutation, QuizReScheduleMutation
from .question import QuestionCreationMutation, QuestionUpdateMutation, QuestionDeleteMutation